name: Checkout and deploy
on:
  push:
    branches: [main, github-actions]

jobs:
  checkout:
    name: 'Checkout'
    runs-on:
      labels: [self-hosted, oracle]
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'

  install_dependancy:
    name: 'Install dependancy'
    needs: [checkout]
    runs-on:
      labels: [self-hosted, oracle]
    steps:
      - uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: npm cache verify
      - run: npm ci

  deploy:
    name: 'Deploy'
    needs: [checkout, install_dependancy]
    runs-on:
      labels: [self-hosted, sangsu]
    steps:
      - run: chmod 777 ./start.sh
      - run: RUNNER_TRACKING_ID="" && ./start.sh
